language: ruby
rvm:
  - 2.2
before_script:
  - gem install awesome_bot
script:
  - awesome_bot *.tex *.md *.bib -a 302,429 --allow-timeout -t 5 --allow-dupe --allow-ssl --white-list http://wals.info/languoid/lect/wals,https://www.cereproc.com/en/CereProc,http://stories.schwa-fire.com/who,https://w3techs.com/technologies/history,https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using,http://www.visualtravelguide.com/Photo-kml.html,https://aclweb.org/aclwiki/List,https://github.com/clab/fast,https://github.com/dkhamsing/awesome,http://dobes.mpi.nl/archive,https://www.qgis.org/,http://www.unesco.org/new/fileadmin/MULTIMEDIA/HQ/CLT/pdf/International,https://scholar.google.com,http://hdl.handle.net
